version: "3.1"
services:
  blue:
    container_name: blue
    image: lomayd/spring-lab-cicd
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
  green:
    container_name: green
    image: lomayd/spring-lab-cicd
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=green